# .github/workflows/deploy.yml
name: Deploy to VPS

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🚀 Deploy to VPS
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: 22
                  script: |
                      cd ~/deployed-site
                      chmod +x deploy-ci.sh
                      ./deploy-ci.sh

            - name: ✅ Deployment Status
              if: success()
              run: echo "Deployment successful!"

            - name: ❌ Deployment Failed
              if: failure()
              run: echo "Deployment failed! Check logs."
